### PR TITLE
Version 1.8

### PR DESCRIPTION
**Pull request by benlk**
## Changes

This is still a WIP, pending #57.

- [x] update the version number to 1.8
- [x] check that contributors are properly attributed
    - inn_nerds -> innlabs on wordpress.org
- [x] update changelog in readme.txt, README.md, and elsewhere for everything in https://github.com/npr/nprapi-wordpress/compare/1.7.1...HEAD
- [x] fix header formatting in README.md
- [x] update release.sh
- [x] updates uses of  "NPR API" to "NPR Story API" in most places, to match plugin and API names.

## post-merge tasts
- [ ] tag release: `git tag -a v1.8 -m "NPR Story API version 1.8"
- [ ] deploy an update to the plugin to WordPress.org

### CODE REVIEW

**Comment by benlk** [comment]
@eteare and @milespj:
This PR just bumps the version number and updates the documentation in a number of places, as described in the PR description.

Once this version number pull request is merged the 'master' branch of this plugin will be ready to be tagged at 1.8 and pushed to wordpress.org. Tagging doesn't happen immediately after release; we can merge this now and wait for your testing to finish before tagging.

**Comment by eteare** [comment]
Ben, I am going to have Paul and Scott just do one last 👍 and then I will merge this PR.

**Comment by benlk** [comment]
✅ zip file generated by the release script runs as a plugin

**Comment by benlk** [comment]
Release tagged: https://github.com/npr/nprapi-wordpress/releases/tag/v1.8

**Comment by benlk** [comment]
Release released: https://wordpress.org/plugins/npr-story-api/advanced/

**Pull request merged**
